version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
      eslint:
        patterns:
          - eslint
          - '@eslint/*'
          - typescript-eslint
      prettier:
        patterns:
          - prettier
          - prettier-plugin-*
      ionic:
        patterns:
          - '@ionic/*'
      capacitor:
        patterns:
          - '@capacitor/*'
          - '@capawesome/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
